### ISSUE TITLE
Scrolling Text

### ISSUE THREAD

**Issue by nibzy26** [nopnop2002/Raspberry-ssd1306#10]
Hi there,
I have a question regarding scrolling text.At the moment I am scrolling it both horizontally and vertically but its not a smooth scroll like i can see a flicker or delay when text moves on the screen 
is there a way we can do a smooth scrolling so that user wont notice a flicker or delay on the screen when the text moves.

Thanks
Nabeel
nibzy26@gmail.com

**Comment by nopnop2002** [comment]
As far as I know, SSD1306 doesn't have hardware scroll function.

You need to scroll one dot at a time by software.

**Comment by nibzy26** [comment]
Hi,

Thanks for your reply.yes I have almost sorted it out .
Just another thing can we use a different font file of larger font size  as
I would like to increase the font size. where can I get the suitable .FNT
file to use with it

Thanks

Nabeel

**Comment by nopnop2002** [comment]
I added extra_fonts.
You can 16/24/32 dot font.

**Comment by nibzy26** [comment]
Thanks,
I just changed the font files and used ILGZ32XB.FNT and ILGH32XB.FNT in the code .
The characters are not showing up ok but a little distorted.
can you pls advise which area of the code I need to change or the page settings etc ?

Thanks

**Comment by nopnop2002** [comment]
You have to change this code.
https://github.com/nopnop2002/Raspberry-ssd1306/blob/master/oled.c#L440

**Comment by nopnop2002** [comment]
I was wrong.
Fonts are defined here.

https://github.com/nopnop2002/Raspberry-ssd1306/blob/master/oled.c#L489

**Comment by nibzy26** [comment]
Hi,
I am using drawSJISChar function only and not drawChar so basically not using line 489 
unsigned char num_str[95][16] =

coul you please further guide me as to what needs to be changed in drawSJISCharfunction for displaying 16 * 32 dot font.
I think there will be 4 memcpy lines  instead of two as now we will write to 4 pages per line caz there will be two lines.

thanks

**Comment by nibzy26** [comment]
if I am not not wrong there will be changes in drawSJISChar function like
unsigned char fonts[64]; // font pattern  for 16 * 32 dot font 
  uint8_t bitmap[128];   // same

and the last 4 lines will be 
memcpy(frame+((x-1)*512)+((y-1)*8),bitmap,pw);
memcpy(frame+(128+(x-1)*512)+((y-1)*8),bitmap+64,pw);
memcpy(frame+256+((x-1)*512)+((y-1)*8),bitmap,pw);
memcpy(frame+384+(128+(x-1)*512)+((y-1)*8),bitmap+64,pw);

return y + pw/16           where pw = 16 and ph = 32  for 16*32 font

**Comment by nopnop2002** [comment]
This rep use 24 and 32 dot font.

https://github.com/nopnop2002/wiringpi-tft-tool

**Comment by nibzy26** [comment]
Hi,
I am using this LCD 0.96 inch 80*160 dot-matrix, ST7735S, 4 wire SPI TFT
LCD module with Orange pi PC2  and trying to use
your wiring pi - tft library
https://github.com/nopnop2002/wiringpi-tft-tool

and have compiled it with

cc -o tft tft.c fontx.c spilib.c -lwiringPi -lm -lpthread -DSPI -DWPI

Q ) can this tool/library work with this particular LCD module ?

Also I am confused about the pin numbers to use in spi.conf file as
there is GPIo number, wiring pi number and physical pin numbering

I have attached the output of gpio readall

which pin numbers should I use for CS and RS ?

Please advise

Many Thanks

Nabeel

**Comment by nopnop2002** [comment]
In WiringPi library, GPIO number is same as RPI.

Pin#3=GPIO2
Pin#5=GPIO3

**Comment by nibzy26** [comment]
Just wondering in this repo
https://github.com/nopnop2002/wiringpi-tft-tool/blob/master/spilib.c
wherever we write like using wiringPiSPIDataRW(CH, &c, 1);  function do we
have to pull CS line low and then High after writing
with digitalWrite(CS,LOW) and digitalWrite(CS,HIGH). ??

I am trying to get it going with OrangePi PC2 which is H5 board but its not
working ..
any advise how to sort it?

Thanks
Nabeel

**Comment by nopnop2002** [comment]
I changed the handling of CS.
https://github.com/nopnop2002/wiringpi-tft-tool/blob/master/spilib.c

It works correctly on OrangePi PC.

It don't work on OrangePi PC2.

I don't know why.

**Comment by nibzy26** [comment]
On PC2 we have SPI 1 available and SPI0 is not caz there is nor flash
attached to SPI0.

Although I have SPI1 working on PC2 but still nothing on the screen .I am
using ST7735 based 160x80 pixel TFT SPI display. (Specifically the 0.96"
SPI LCD from Pimoroni).

**Comment by nibzy26** [comment]
Hi,

Now its working on pc plus for me thanks, what about Horizontal scrolling
of text ? I am currently trying to implement horizontal scrolling of text ,
any ideas what needs to be changed ?

Nabeel

**Comment by nopnop2002** [comment]
To do horizontal scrolling:
display
Display data is shifted (rotation) by 1 dot or 1 byte
Redisplay

**Comment by Drom0s137** [comment]
Hi @nibzy26,

I am attempting to stop the flickering as well and would greatly appreciate it if you could share your solution on that for this repo.

Eddy

**Comment by nopnop2002** [comment]
@Drom0s137 

Are you calling in a loop like this?


```
for i in {1..10} ; do
    sudo ./oled s
done
```

**Comment by Drom0s137** [comment]
@nopnop2002 
I noticed that I was just reinitializing the screen all the time. the issue has been fixed, thank you.
