### ISSUE TITLE
Adding text returns error code 1

### ISSUE THREAD

**Issue by ctschach** [nopnop2002/Raspberry-ssd1306#14]
Hi,

I tried using oled in /etc/rc.local to print a message like the IP address. it's not working, so I looked a bit into it.

The problem is, that the command:

`./oled +a "Booting..."`

Delivers Exit Code 1 which causes /etc/rc.local to terminate. So what's the reason for returning a none-zero exit code here?

**Comment by nopnop2002** [comment]
@ctschach 

It works fine when run from the command line.
However, it does not work properly when executed in rc.local.
Maybe permissions are affecting it.

**Comment by ctschach** [comment]
No, that's not the problem. If you execute 

`./oled +a "Booting..." &`

To run it in the background, it will terminated with Exit Code 1 which is causing the /etc/rc.local to stop immediately.

The question is, why do you have a "return 1" in most of the code lines instead of "return 0"? Is there any particular reason?

**Comment by nopnop2002** [comment]
Is retun1 a problem when running commands in /etc/rc.local?

**Comment by ctschach** [comment]
But adding the "&" is a simple way to receive the exit code of a program.

The /etc/rc.local is calling the shell with "-e" parameter which according the to man page:

>            -e errexit       If not interactive, exit immediately if any untested command fails.  The exit status of a command is considered to be explicitly tested if the command is used to control an if, elif, while, or until; or if the
>                             command is the left hand operand of an “&&” or “||” operator.
> 

So when a command returns an exit code not equal to "0" it will terminate the script.

**Comment by nopnop2002** [comment]
oled returns 1 on successful completion.

**Comment by ctschach** [comment]
And exactly this is a problem. An exit code not equal to "0" is seen as a "unnormal" exit.

Like it's referenced here: https://tldp.org/LDP/abs/html/exitcodes.html

> #!/bin/bash
> 
> cat file.txt 
> 
> if [ $? -eq 0 ]
> then
>   echo "The script ran ok"
>   exit 0
> else
>   echo "The script failed" >&2
>   exit 1
> fi

**Comment by nopnop2002** [comment]
OK
I changed exit code.
