### ISSUE TITLE
OLED 1.3" displays with SH1106 

### ISSUE THREAD

**Issue by zrdimetc** [nopnop2002/Raspberry-ssd1306#16]
Hi and thank you for creating such a great tool for working with 0.96 and 0.91 OLED displays with SSD1306. 0.96" OLED is probably the most widely used in any projects from all of the OLED screen sizes. 1.3" OLED's are also highly popular, less stressful to the eyes, with much better readability. However, many of 1.3" OLED's come with SH1106 chip instead of SSD1306. OLED's with SH1106 are nearly identical to SSD1306 and can be initialized in a similar way, but their geometry is slightly "offset". 1.3" OLED's SH1106 chip memory works with 132x64 pixels instead of 128x64 in SSD1306. Is there anything we can change in `oled.c` to try to support 1.3" OLED with SH1106? Currently the 1.3" displays will initialize, but the printing to screen will be very much offset. Running `test.sh` or trying to command the display to print text to any of the rows will show somewhere in the first row clearly broken. It would be great if both 0.96" and 1.3" OLED's could be supported? Regards,

**Comment by nopnop2002** [comment]
@zrdimetc 

I just ordered the 1.3 inch and 0.96 inch SH1106.

**Comment by zrdimetc** [comment]
That's great. Thank you very much for considering support for that category of OLED. This is [SSH1106 Datasheet](https://www.elecrow.com/download/SH1106%20datasheet.pdf)

**Comment by nopnop2002** [comment]
@zrdimetc 

![OLED-SH1106](https://user-images.githubusercontent.com/6020549/106369676-d1bcfd00-6396-11eb-9ee1-def716424411.JPG)
![OLED-SH1106](https://user-images.githubusercontent.com/6020549/106369677-d5e91a80-6396-11eb-9ffe-81c4d6f3947f.JPG)

**Comment by zrdimetc** [comment]
Dear nopnop2002, thank you so much for adding support for SSH1106 so quickly. I tried the latest code with 1.3 inch I2C OLED display. Everything works perfect, after adding the offset. 1.3 inch displays are very easy to read. Your library is very comprehensive, covering a great majority of OLED displays that people use in projects. There will still be a few OLED displays like 1.44 and 1.8 inch or other sizes unsupported, but they are not so common in projects. They can maybe become a project at another time... Your OLED library is truly amazing! Best regards, Zoran.
